### ISSUE TITLE
NodeMCU_Amica_R2 mounting holes

### ISSUE THREAD

**Issue by peternlewis** [skorokithakis/kicad-lib#2]
I made a board with a NodeMCU on it, and used your NodeMCU_Amica_R2.kicad_mod.

I don't know if it is just the ones I have, but the mounting holes in the drawing are not in the right place for me.  I adjusted them in a printout and then had the board made and my adjusted ones are pretty close to correct, much closer than the ones in the drawing on your footprint.

I'm not sure how best to report the more accurate positions.  I'd be happy to privately email you my kicad board files so you can see where I put the mounting holes, or measure the offsets with Kicad perhaps.  But if your mounting holes for your NodeMCUs line up ok, then maybe they just vary (heaven knows the NodeMCU version naming is insane).  

Regardless, thanks for making this available, it still saved me a bunch of time.

**Comment by skorokithakis** [comment]
Ah, thank you for the ticket. Yes, the mounting holes may not be exact, as I never use them so I haven't had an opportunity to test them.

Do you have the modified component? If not, yes, please email me what you have and I will fix mine. My email is on my site, https://www.stavros.io.

Thank you!

**Comment by peternlewis** [comment]
I have emailed you a PCB with the NodeMCU and 4 reference holes.  I printed it and my holes were pretty close, one pair was out by about half a mm, and I have adjusted it in the document I emailed you, so if you adjust the footprint holes to match those, then they should be very close to accurate.

Thanks!

**Comment by skorokithakis** [comment]
Fixed, thank you!
